apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-data
  namespace: s13-webapp
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
