# Static PersistentVolume created by hand (the "admin" way).
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s13-student-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/s13-student-data
