{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pragya-webapp.serviceAccountName" . }}
  labels:
    {{- include "pragya-webapp.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
